name: adya
description: Assignment for Adya Health.  A non-linear video session system

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18

  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  fluro: ^2.0.5
  video_player: ^2.6.1
  google_fonts: 5.1.0
  lottie: ^2.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/captions/
    - assets/lotties/
